// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Composable, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAccountData, DeleteAccountError, DeleteAccountResponse, DeleteAdminUsersByUserIdData, DeleteAdminUsersByUserIdError, DeleteAdminUsersByUserIdResponse, GetAccountData, GetAccountError, GetAccountResponse, GetAdminUsersByUserIdData, GetAdminUsersByUserIdError, GetAdminUsersByUserIdResponse, GetAdminUsersData, GetAdminUsersResponse, GetAuthSessionData, GetAuthSessionError, GetAuthSessionResponse, GetUsersSearchData, GetUsersSearchError, GetUsersSearchResponse, PostAdminUsersData, PostAdminUsersError, PostAdminUsersResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthResetPasswordData, PostAuthResetPasswordError, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestError, PostAuthResetPasswordRequestResponse, PostAuthResetPasswordResponse, PutAccountData, PutAccountError, PutAccountPasswordData, PutAccountPasswordError, PutAccountPasswordResponse, PutAccountResponse, PutAdminUsersByUserIdData, PutAdminUsersByUserIdError, PutAdminUsersByUserIdPasswordData, PutAdminUsersByUserIdPasswordError, PutAdminUsersByUserIdPasswordResponse, PutAdminUsersByUserIdResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>): any => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <TComposable extends Composable = '$fetch', DefaultT extends GetAuthSessionResponse = GetAuthSessionResponse>(options: Options<TComposable, GetAuthSessionData, GetAuthSessionResponse, DefaultT>): any => (options.client ?? client).get<TComposable, GetAuthSessionResponse | DefaultT, GetAuthSessionError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * User Logout
 *
 * Invalidate the current user's session
 */
export const postAuthLogout = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLogoutResponse = PostAuthLogoutResponse>(options: Options<TComposable, PostAuthLogoutData, PostAuthLogoutResponse, DefaultT>): any => (options.client ?? client).post<TComposable, PostAuthLogoutResponse | DefaultT, PostAuthLogoutError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Reset your password for reset token
 *
 * Reset your password using a valid reset token
 */
export const postAuthResetPassword = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordResponse = PostAuthResetPasswordResponse>(options: Options<TComposable, PostAuthResetPasswordData, PostAuthResetPasswordResponse, DefaultT>): any => (options.client ?? client).post<TComposable, PostAuthResetPasswordResponse | DefaultT, PostAuthResetPasswordError, DefaultT>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request Password Reset
 *
 * Request a password reset for a user using their username
 */
export const postAuthResetPasswordRequest = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponse>(options: Options<TComposable, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestResponse, DefaultT>): any => (options.client ?? client).post<TComposable, PostAuthResetPasswordRequestResponse | DefaultT, PostAuthResetPasswordRequestError, DefaultT>({
    url: '/auth/reset-password/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete account
 *
 * Permanently delete the authenticated user's account.
 */
export const deleteAccount = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountResponse = DeleteAccountResponse>(options: Options<TComposable, DeleteAccountData, DeleteAccountResponse, DefaultT>): any => (options.client ?? client).delete<TComposable, DeleteAccountResponse | DefaultT, DeleteAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Get account information
 *
 * Retrieve information about the authenticated user's account.
 */
export const getAccount = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountResponse = GetAccountResponse>(options: Options<TComposable, GetAccountData, GetAccountResponse, DefaultT>): any => (options.client ?? client).get<TComposable, GetAccountResponse | DefaultT, GetAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Update account information
 *
 * Update information about the authenticated user's account.
 */
export const putAccount = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountResponse = PutAccountResponse>(options: Options<TComposable, PutAccountData, PutAccountResponse, DefaultT>): any => (options.client ?? client).put<TComposable, PutAccountResponse | DefaultT, PutAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change account password
 *
 * Change the password of the authenticated user's account.
 */
export const putAccountPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountPasswordResponse = PutAccountPasswordResponse>(options: Options<TComposable, PutAccountPasswordData, PutAccountPasswordResponse, DefaultT>): any => (options.client ?? client).put<TComposable, PutAccountPasswordResponse | DefaultT, PutAccountPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 *
 * Retrieve LeiCraft_MC Status Page accounts with optional role and search filters.
 */
export const getAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersResponse = GetAdminUsersResponse>(options: Options<TComposable, GetAdminUsersData, GetAdminUsersResponse, DefaultT>): any => (options.client ?? client).get<TComposable, GetAdminUsersResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create user
 *
 * Provision a new LeiCraft_MC Status Page account with the desired role.
 */
export const postAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends PostAdminUsersResponse = PostAdminUsersResponse>(options: Options<TComposable, PostAdminUsersData, PostAdminUsersResponse, DefaultT>): any => (options.client ?? client).post<TComposable, PostAdminUsersResponse | DefaultT, PostAdminUsersError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 *
 * Permanently remove a LeiCraft_MC Status Page account.
 */
export const deleteAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponse>(options: Options<TComposable, DeleteAdminUsersByUserIdData, DeleteAdminUsersByUserIdResponse, DefaultT>): any => (options.client ?? client).delete<TComposable, DeleteAdminUsersByUserIdResponse | DefaultT, DeleteAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Get user
 *
 * Retrieve details for a specific LeiCraft_MC Status Page account.
 */
export const getAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponse>(options: Options<TComposable, GetAdminUsersByUserIdData, GetAdminUsersByUserIdResponse, DefaultT>): any => (options.client ?? client).get<TComposable, GetAdminUsersByUserIdResponse | DefaultT, GetAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Modify profile fields or role for a LeiCraft_MC Status Page account.
 */
export const putAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponse>(options: Options<TComposable, PutAdminUsersByUserIdData, PutAdminUsersByUserIdResponse, DefaultT>): any => (options.client ?? client).put<TComposable, PutAdminUsersByUserIdResponse | DefaultT, PutAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 *
 * Set a new password for a LeiCraft_MC Status Page account and revoke active sessions.
 */
export const putAdminUsersByUserIdPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponse>(options: Options<TComposable, PutAdminUsersByUserIdPasswordData, PutAdminUsersByUserIdPasswordResponse, DefaultT>): any => (options.client ?? client).put<TComposable, PutAdminUsersByUserIdPasswordResponse | DefaultT, PutAdminUsersByUserIdPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search users
 *
 * Find other users by username or display name. Returns public profile fields only.
 */
export const getUsersSearch = <TComposable extends Composable = '$fetch', DefaultT extends GetUsersSearchResponse = GetUsersSearchResponse>(options: Options<TComposable, GetUsersSearchData, GetUsersSearchResponse, DefaultT>): any => (options.client ?? client).get<TComposable, GetUsersSearchResponse | DefaultT, GetUsersSearchError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/search',
    ...options
});
