// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:12336/api/v1/' | 'https://status.leicraftmc.com/api/v1/' | (string & {});
};

export type PostAuthLoginData = {
    body: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Invalid username or password / You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'Invalid username or password / You are already authenticated';
    };
    /**
     * Too many login attempts. Try again later.
     */
    429: {
        success: false;
        code: 429;
        message: 'Too many login attempts. Try again later.';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Login successful';
        data: {
            user_id: number;
            user_role: 'admin' | 'member';
            created_at: number;
            expires_at: number;
            token: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Session info retrieved successfully';
        data: {
            user_id: number;
            user_role: 'admin' | 'member';
            created_at: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token / Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Unauthorized: Invalid or missing session token / Your Auth Context is not a session';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        code: 200;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostAuthResetPasswordData = {
    body: {
        reset_token: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * You are already authenticated
     */
    401: {
        success: false;
        code: 401;
        message: 'You are already authenticated';
    };
    /**
     * User for reset token not found
     */
    500: {
        success: false;
        code: 500;
        message: 'User for reset token not found';
    };
};

export type PostAuthResetPasswordError = PostAuthResetPasswordErrors[keyof PostAuthResetPasswordErrors];

export type PostAuthResetPasswordResponses = {
    /**
     * Password has been reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password has been reset successfully';
        data: null;
    };
};

export type PostAuthResetPasswordResponse = PostAuthResetPasswordResponses[keyof PostAuthResetPasswordResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountErrors = {
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'member';
            created_at: number;
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
    } & {
        /**
         * Current password — required to confirm account changes
         */
        current_password: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
    /**
     * Username or email already in use
     */
    409: {
        success: false;
        code: 409;
        message: 'Username or email already in use';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Current password is incorrect / Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Current password is incorrect / Syntax or validation error in request';
    };
    /**
     * Your Auth Context is not a session
     */
    401: {
        success: false;
        code: 401;
        message: 'Your Auth Context is not a session';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type GetAccountApikeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type GetAccountApikeysResponses = {
    /**
     * API keys retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API keys retrieved successfully';
        data: Array<{
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        }>;
    };
};

export type GetAccountApikeysResponse = GetAccountApikeysResponses[keyof GetAccountApikeysResponses];

export type PostAccountApikeysData = {
    body: {
        description: string;
        expires_at: '7d' | '30d' | '90d' | '180d' | '365d' | null;
    };
    path?: never;
    query?: never;
    url: '/account/apikeys';
};

export type PostAccountApikeysErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostAccountApikeysError = PostAccountApikeysErrors[keyof PostAccountApikeysErrors];

export type PostAccountApikeysResponses = {
    /**
     * API key created successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key created successfully';
        data: {
            id: string;
            token: string;
        };
    };
};

export type PostAccountApikeysResponse = PostAccountApikeysResponses[keyof PostAccountApikeysResponses];

export type DeleteAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type DeleteAccountApikeysByApiKeyIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type DeleteAccountApikeysByApiKeyIdError = DeleteAccountApikeysByApiKeyIdErrors[keyof DeleteAccountApikeysByApiKeyIdErrors];

export type DeleteAccountApikeysByApiKeyIdResponses = {
    /**
     * API key deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key deleted successfully';
        data: null;
    };
};

export type DeleteAccountApikeysByApiKeyIdResponse = DeleteAccountApikeysByApiKeyIdResponses[keyof DeleteAccountApikeysByApiKeyIdResponses];

export type GetAccountApikeysByApiKeyIdData = {
    body?: never;
    path: {
        apiKeyID: string;
    };
    query?: never;
    url: '/account/apikeys/{apiKeyID}';
};

export type GetAccountApikeysByApiKeyIdErrors = {
    /**
     * API key not found
     */
    404: {
        success: false;
        code: 404;
        message: 'API key not found';
    };
};

export type GetAccountApikeysByApiKeyIdError = GetAccountApikeysByApiKeyIdErrors[keyof GetAccountApikeysByApiKeyIdErrors];

export type GetAccountApikeysByApiKeyIdResponses = {
    /**
     * API key retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'API key retrieved successfully';
        data: {
            id: string;
            description: string;
            created_at: number;
            expires_at: number | null;
        };
    };
};

export type GetAccountApikeysByApiKeyIdResponse = GetAccountApikeysByApiKeyIdResponses[keyof GetAccountApikeysByApiKeyIdResponses];

export type GetAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        role?: 'admin' | 'member';
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/admin/users';
};

export type GetAdminUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'member';
            created_at: number;
        }>;
    };
};

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];

export type PostAdminUsersData = {
    body: {
        username: string;
        display_name: string;
        email: string;
        role?: 'admin' | 'member';
        password: string;
    };
    path?: never;
    query?: never;
    url: '/admin/users';
};

export type PostAdminUsersErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PostAdminUsersError = PostAdminUsersErrors[keyof PostAdminUsersErrors];

export type PostAdminUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'User created successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'member';
            created_at: number;
        };
    };
};

export type PostAdminUsersResponse = PostAdminUsersResponses[keyof PostAdminUsersResponses];

export type DeleteAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type DeleteAdminUsersByUserIdErrors = {
    /**
     * Cannot delete the last remaining administrator
     */
    400: {
        success: false;
        code: 400;
        message: 'Cannot delete the last remaining administrator';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type DeleteAdminUsersByUserIdError = DeleteAdminUsersByUserIdErrors[keyof DeleteAdminUsersByUserIdErrors];

export type DeleteAdminUsersByUserIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User deleted successfully';
        data: null;
    };
};

export type DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponses[keyof DeleteAdminUsersByUserIdResponses];

export type GetAdminUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetAdminUsersByUserIdErrors = {
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type GetAdminUsersByUserIdError = GetAdminUsersByUserIdErrors[keyof GetAdminUsersByUserIdErrors];

export type GetAdminUsersByUserIdResponses = {
    /**
     * User retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User retrieved successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'member';
            created_at: number;
        };
    };
};

export type GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponses[keyof GetAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdData = {
    body: {
        username?: string;
        display_name?: string;
        email?: string;
        role?: 'admin' | 'member';
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type PutAdminUsersByUserIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
    /**
     * Conflict: Username or email already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'Conflict: Username or email already exists';
    };
};

export type PutAdminUsersByUserIdError = PutAdminUsersByUserIdErrors[keyof PutAdminUsersByUserIdErrors];

export type PutAdminUsersByUserIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'User updated successfully';
        data: {
            id: number;
            username: string;
            display_name: string;
            email: string;
            role: 'admin' | 'member';
            created_at: number;
        };
    };
};

export type PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponses[keyof PutAdminUsersByUserIdResponses];

export type PutAdminUsersByUserIdPasswordData = {
    body: {
        /**
         * New password for the account
         */
        password: string;
    };
    path: {
        userId: number;
    };
    query?: never;
    url: '/admin/users/{userId}/password';
};

export type PutAdminUsersByUserIdPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * User not found
     */
    404: {
        success: false;
        code: 404;
        message: 'User not found';
    };
};

export type PutAdminUsersByUserIdPasswordError = PutAdminUsersByUserIdPasswordErrors[keyof PutAdminUsersByUserIdPasswordErrors];

export type PutAdminUsersByUserIdPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Password reset successfully';
        data: null;
    };
};

export type PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponses[keyof PutAdminUsersByUserIdPasswordResponses];

export type GetAdminMonitorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/monitors';
};

export type GetAdminMonitorsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminMonitorsError = GetAdminMonitorsErrors[keyof GetAdminMonitorsErrors];

export type GetAdminMonitorsResponses = {
    /**
     * Monitors retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitors retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
        }>;
    };
};

export type GetAdminMonitorsResponse = GetAdminMonitorsResponses[keyof GetAdminMonitorsResponses];

export type PostAdminMonitorsData = {
    body: {
        name: string;
        type: 'http' | 'tcp';
        target: string;
        interval_seconds: number;
        timeout_seconds: number;
        http_method?: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';
        expected_http_status?: number;
        follow_redirects?: boolean;
        verify_tls?: boolean;
        is_enabled?: boolean;
    };
    path?: never;
    query?: never;
    url: '/admin/monitors';
};

export type PostAdminMonitorsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * A monitor with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'A monitor with this name already exists';
    };
};

export type PostAdminMonitorsError = PostAdminMonitorsErrors[keyof PostAdminMonitorsErrors];

export type PostAdminMonitorsResponses = {
    /**
     * Monitor created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Monitor created successfully';
        data: {
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
        };
    };
};

export type PostAdminMonitorsResponse = PostAdminMonitorsResponses[keyof PostAdminMonitorsResponses];

export type DeleteAdminMonitorsByMonitorIdData = {
    body?: never;
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/admin/monitors/{monitorId}';
};

export type DeleteAdminMonitorsByMonitorIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found';
    };
};

export type DeleteAdminMonitorsByMonitorIdError = DeleteAdminMonitorsByMonitorIdErrors[keyof DeleteAdminMonitorsByMonitorIdErrors];

export type DeleteAdminMonitorsByMonitorIdResponses = {
    /**
     * Monitor deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor deleted successfully';
        data: null;
    };
};

export type DeleteAdminMonitorsByMonitorIdResponse = DeleteAdminMonitorsByMonitorIdResponses[keyof DeleteAdminMonitorsByMonitorIdResponses];

export type GetAdminMonitorsByMonitorIdData = {
    body?: never;
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/admin/monitors/{monitorId}';
};

export type GetAdminMonitorsByMonitorIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found';
    };
};

export type GetAdminMonitorsByMonitorIdError = GetAdminMonitorsByMonitorIdErrors[keyof GetAdminMonitorsByMonitorIdErrors];

export type GetAdminMonitorsByMonitorIdResponses = {
    /**
     * Monitor retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor retrieved successfully';
        data: {
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
        };
    };
};

export type GetAdminMonitorsByMonitorIdResponse = GetAdminMonitorsByMonitorIdResponses[keyof GetAdminMonitorsByMonitorIdResponses];

export type PutAdminMonitorsByMonitorIdData = {
    body: {
        name?: string;
        type?: 'http' | 'tcp';
        target?: string;
        interval_seconds?: number;
        timeout_seconds?: number;
        http_method?: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';
        expected_http_status?: number;
        follow_redirects?: boolean;
        verify_tls?: boolean;
        is_enabled?: boolean;
    };
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/admin/monitors/{monitorId}';
};

export type PutAdminMonitorsByMonitorIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found';
    };
    /**
     * A monitor with this name already exists
     */
    409: {
        success: false;
        code: 409;
        message: 'A monitor with this name already exists';
    };
};

export type PutAdminMonitorsByMonitorIdError = PutAdminMonitorsByMonitorIdErrors[keyof PutAdminMonitorsByMonitorIdErrors];

export type PutAdminMonitorsByMonitorIdResponses = {
    /**
     * Monitor updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor updated successfully';
        data: {
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
        };
    };
};

export type PutAdminMonitorsByMonitorIdResponse = PutAdminMonitorsByMonitorIdResponses[keyof PutAdminMonitorsByMonitorIdResponses];

export type PostAdminMonitorsByMonitorIdCheckData = {
    body?: never;
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/admin/monitors/{monitorId}/check';
};

export type PostAdminMonitorsByMonitorIdCheckErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found';
    };
};

export type PostAdminMonitorsByMonitorIdCheckError = PostAdminMonitorsByMonitorIdCheckErrors[keyof PostAdminMonitorsByMonitorIdCheckErrors];

export type PostAdminMonitorsByMonitorIdCheckResponses = {
    /**
     * Monitor check completed
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor check completed';
        data: {
            check: {
                id: number;
                monitor_id: number;
                status: 'up' | 'down' | 'degraded' | 'unknown';
                response_time_ms: number | null;
                checked_at: number;
            };
        };
    };
};

export type PostAdminMonitorsByMonitorIdCheckResponse = PostAdminMonitorsByMonitorIdCheckResponses[keyof PostAdminMonitorsByMonitorIdCheckResponses];

export type GetAdminStatusPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page';
};

export type GetAdminStatusPageErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageError = GetAdminStatusPageErrors[keyof GetAdminStatusPageErrors];

export type GetAdminStatusPageResponses = {
    /**
     * Status page retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Status page retrieved successfully';
        data: {
            config: {
                id: number;
                title: string;
                description: string | null;
                is_public: boolean;
                is_enabled: boolean;
                theme: 'light' | 'dark' | 'auto';
                created_at: number;
                updated_at: number;
            };
            groups: Array<{
                id: number;
                name: string;
                sort_order: number;
            }>;
            links: Array<{
                id: number;
                monitor_id: number;
                group_id: number | null;
                display_name: string | null;
                sort_order: number;
                monitor_name: string;
            }>;
        };
    };
};

export type GetAdminStatusPageResponse = GetAdminStatusPageResponses[keyof GetAdminStatusPageResponses];

export type PutAdminStatusPageData = {
    body: {
        title?: string;
        description?: string;
        is_public?: boolean;
        is_enabled?: boolean;
        theme?: 'light' | 'dark' | 'auto';
    };
    path?: never;
    query?: never;
    url: '/admin/status-page';
};

export type PutAdminStatusPageErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PutAdminStatusPageError = PutAdminStatusPageErrors[keyof PutAdminStatusPageErrors];

export type PutAdminStatusPageResponses = {
    /**
     * Status page updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Status page updated successfully';
        data: {
            id: number;
            title: string;
            description: string | null;
            is_public: boolean;
            is_enabled: boolean;
            theme: 'light' | 'dark' | 'auto';
            created_at: number;
            updated_at: number;
        };
    };
};

export type PutAdminStatusPageResponse = PutAdminStatusPageResponses[keyof PutAdminStatusPageResponses];

export type GetAdminStatusPageGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page/groups';
};

export type GetAdminStatusPageGroupsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageGroupsError = GetAdminStatusPageGroupsErrors[keyof GetAdminStatusPageGroupsErrors];

export type GetAdminStatusPageGroupsResponses = {
    /**
     * Groups retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Groups retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            sort_order: number;
        }>;
    };
};

export type GetAdminStatusPageGroupsResponse = GetAdminStatusPageGroupsResponses[keyof GetAdminStatusPageGroupsResponses];

export type PostAdminStatusPageGroupsData = {
    body: {
        name: string;
        sort_order?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/status-page/groups';
};

export type PostAdminStatusPageGroupsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PostAdminStatusPageGroupsError = PostAdminStatusPageGroupsErrors[keyof PostAdminStatusPageGroupsErrors];

export type PostAdminStatusPageGroupsResponses = {
    /**
     * Group created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Group created successfully';
        data: {
            id: number;
            name: string;
            sort_order: number;
        };
    };
};

export type PostAdminStatusPageGroupsResponse = PostAdminStatusPageGroupsResponses[keyof PostAdminStatusPageGroupsResponses];

export type DeleteAdminStatusPageGroupsByGroupIdData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/admin/status-page/groups/{groupId}';
};

export type DeleteAdminStatusPageGroupsByGroupIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Group not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Group not found';
    };
};

export type DeleteAdminStatusPageGroupsByGroupIdError = DeleteAdminStatusPageGroupsByGroupIdErrors[keyof DeleteAdminStatusPageGroupsByGroupIdErrors];

export type DeleteAdminStatusPageGroupsByGroupIdResponses = {
    /**
     * Group deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Group deleted successfully';
        data: null;
    };
};

export type DeleteAdminStatusPageGroupsByGroupIdResponse = DeleteAdminStatusPageGroupsByGroupIdResponses[keyof DeleteAdminStatusPageGroupsByGroupIdResponses];

export type PutAdminStatusPageGroupsByGroupIdData = {
    body: {
        name?: string;
        sort_order?: number;
    };
    path: {
        groupId: number;
    };
    query?: never;
    url: '/admin/status-page/groups/{groupId}';
};

export type PutAdminStatusPageGroupsByGroupIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Group not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Group not found';
    };
};

export type PutAdminStatusPageGroupsByGroupIdError = PutAdminStatusPageGroupsByGroupIdErrors[keyof PutAdminStatusPageGroupsByGroupIdErrors];

export type PutAdminStatusPageGroupsByGroupIdResponses = {
    /**
     * Group updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Group updated successfully';
        data: {
            id: number;
            name: string;
            sort_order: number;
        };
    };
};

export type PutAdminStatusPageGroupsByGroupIdResponse = PutAdminStatusPageGroupsByGroupIdResponses[keyof PutAdminStatusPageGroupsByGroupIdResponses];

export type GetAdminStatusPageMonitorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page/monitors';
};

export type GetAdminStatusPageMonitorsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageMonitorsError = GetAdminStatusPageMonitorsErrors[keyof GetAdminStatusPageMonitorsErrors];

export type GetAdminStatusPageMonitorsResponses = {
    /**
     * Links retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Links retrieved successfully';
        data: Array<{
            id: number;
            monitor_id: number;
            group_id: number | null;
            display_name: string | null;
            sort_order: number;
            monitor_name: string;
        }>;
    };
};

export type GetAdminStatusPageMonitorsResponse = GetAdminStatusPageMonitorsResponses[keyof GetAdminStatusPageMonitorsResponses];

export type PostAdminStatusPageMonitorsData = {
    body: {
        monitor_id: number;
        group_id?: number;
        display_name?: string;
        sort_order?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/status-page/monitors';
};

export type PostAdminStatusPageMonitorsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Status page or monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page or monitor not found';
    };
    /**
     * Monitor is already linked to the status page
     */
    409: {
        success: false;
        code: 409;
        message: 'Monitor is already linked to the status page';
    };
};

export type PostAdminStatusPageMonitorsError = PostAdminStatusPageMonitorsErrors[keyof PostAdminStatusPageMonitorsErrors];

export type PostAdminStatusPageMonitorsResponses = {
    /**
     * Monitor linked successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Monitor linked successfully';
        data: {
            link: {
                id: number;
                monitor_id: number;
                group_id: number | null;
                display_name: string | null;
                sort_order: number;
            };
        };
    };
};

export type PostAdminStatusPageMonitorsResponse = PostAdminStatusPageMonitorsResponses[keyof PostAdminStatusPageMonitorsResponses];

export type DeleteAdminStatusPageMonitorsByLinkIdData = {
    body?: never;
    path: {
        linkId: number;
    };
    query?: never;
    url: '/admin/status-page/monitors/{linkId}';
};

export type DeleteAdminStatusPageMonitorsByLinkIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor link not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor link not found';
    };
};

export type DeleteAdminStatusPageMonitorsByLinkIdError = DeleteAdminStatusPageMonitorsByLinkIdErrors[keyof DeleteAdminStatusPageMonitorsByLinkIdErrors];

export type DeleteAdminStatusPageMonitorsByLinkIdResponses = {
    /**
     * Monitor unlinked successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor unlinked successfully';
        data: null;
    };
};

export type DeleteAdminStatusPageMonitorsByLinkIdResponse = DeleteAdminStatusPageMonitorsByLinkIdResponses[keyof DeleteAdminStatusPageMonitorsByLinkIdResponses];

export type PutAdminStatusPageMonitorsByLinkIdData = {
    body: {
        group_id?: number | null;
        display_name?: string | null;
        sort_order?: number;
    };
    path: {
        linkId: number;
    };
    query?: never;
    url: '/admin/status-page/monitors/{linkId}';
};

export type PutAdminStatusPageMonitorsByLinkIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Monitor link not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor link not found';
    };
};

export type PutAdminStatusPageMonitorsByLinkIdError = PutAdminStatusPageMonitorsByLinkIdErrors[keyof PutAdminStatusPageMonitorsByLinkIdErrors];

export type PutAdminStatusPageMonitorsByLinkIdResponses = {
    /**
     * Monitor link updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor link updated successfully';
        data: {
            link: {
                id: number;
                monitor_id: number;
                group_id: number | null;
                display_name: string | null;
                sort_order: number;
            };
        };
    };
};

export type PutAdminStatusPageMonitorsByLinkIdResponse = PutAdminStatusPageMonitorsByLinkIdResponses[keyof PutAdminStatusPageMonitorsByLinkIdResponses];

export type GetAdminStatusPageIncidentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page/incidents';
};

export type GetAdminStatusPageIncidentsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageIncidentsError = GetAdminStatusPageIncidentsErrors[keyof GetAdminStatusPageIncidentsErrors];

export type GetAdminStatusPageIncidentsResponses = {
    /**
     * Incidents retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Incidents retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
            severity: 'critical' | 'major' | 'minor' | 'maintenance';
            is_resolved: boolean;
            started_at: number;
            resolved_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetAdminStatusPageIncidentsResponse = GetAdminStatusPageIncidentsResponses[keyof GetAdminStatusPageIncidentsResponses];

export type PostAdminStatusPageIncidentsData = {
    body: {
        title: string;
        message: string;
        status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
        severity: 'critical' | 'major' | 'minor' | 'maintenance';
    };
    path?: never;
    query?: never;
    url: '/admin/status-page/incidents';
};

export type PostAdminStatusPageIncidentsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PostAdminStatusPageIncidentsError = PostAdminStatusPageIncidentsErrors[keyof PostAdminStatusPageIncidentsErrors];

export type PostAdminStatusPageIncidentsResponses = {
    /**
     * Incident created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Incident created successfully';
        data: {
            id: number;
            title: string;
            message: string;
            status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
            severity: 'critical' | 'major' | 'minor' | 'maintenance';
            is_resolved: boolean;
            started_at: number;
            resolved_at: number | null;
            created_at: number;
            updated_at: number;
        };
    };
};

export type PostAdminStatusPageIncidentsResponse = PostAdminStatusPageIncidentsResponses[keyof PostAdminStatusPageIncidentsResponses];

export type DeleteAdminStatusPageIncidentsByIncidentIdData = {
    body?: never;
    path: {
        incidentId: number;
    };
    query?: never;
    url: '/admin/status-page/incidents/{incidentId}';
};

export type DeleteAdminStatusPageIncidentsByIncidentIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Incident not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Incident not found';
    };
};

export type DeleteAdminStatusPageIncidentsByIncidentIdError = DeleteAdminStatusPageIncidentsByIncidentIdErrors[keyof DeleteAdminStatusPageIncidentsByIncidentIdErrors];

export type DeleteAdminStatusPageIncidentsByIncidentIdResponses = {
    /**
     * Incident deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Incident deleted successfully';
        data: null;
    };
};

export type DeleteAdminStatusPageIncidentsByIncidentIdResponse = DeleteAdminStatusPageIncidentsByIncidentIdResponses[keyof DeleteAdminStatusPageIncidentsByIncidentIdResponses];

export type PutAdminStatusPageIncidentsByIncidentIdData = {
    body: {
        title?: string;
        message?: string;
        status?: 'investigating' | 'identified' | 'monitoring' | 'resolved';
        severity?: 'critical' | 'major' | 'minor' | 'maintenance';
        is_resolved?: boolean;
    };
    path: {
        incidentId: number;
    };
    query?: never;
    url: '/admin/status-page/incidents/{incidentId}';
};

export type PutAdminStatusPageIncidentsByIncidentIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Incident not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Incident not found';
    };
};

export type PutAdminStatusPageIncidentsByIncidentIdError = PutAdminStatusPageIncidentsByIncidentIdErrors[keyof PutAdminStatusPageIncidentsByIncidentIdErrors];

export type PutAdminStatusPageIncidentsByIncidentIdResponses = {
    /**
     * Incident updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Incident updated successfully';
        data: {
            id: number;
            title: string;
            message: string;
            status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
            severity: 'critical' | 'major' | 'minor' | 'maintenance';
            is_resolved: boolean;
            started_at: number;
            resolved_at: number | null;
            created_at: number;
            updated_at: number;
        };
    };
};

export type PutAdminStatusPageIncidentsByIncidentIdResponse = PutAdminStatusPageIncidentsByIncidentIdResponses[keyof PutAdminStatusPageIncidentsByIncidentIdResponses];

export type GetAdminStatusPageMaintenanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page/maintenance';
};

export type GetAdminStatusPageMaintenanceErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageMaintenanceError = GetAdminStatusPageMaintenanceErrors[keyof GetAdminStatusPageMaintenanceErrors];

export type GetAdminStatusPageMaintenanceResponses = {
    /**
     * Maintenance retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Maintenance retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
            scheduled_start_at: number;
            scheduled_end_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetAdminStatusPageMaintenanceResponse = GetAdminStatusPageMaintenanceResponses[keyof GetAdminStatusPageMaintenanceResponses];

export type PostAdminStatusPageMaintenanceData = {
    body: {
        title: string;
        message: string;
        status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
        scheduled_start_at: number;
        scheduled_end_at?: number;
    };
    path?: never;
    query?: never;
    url: '/admin/status-page/maintenance';
};

export type PostAdminStatusPageMaintenanceErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PostAdminStatusPageMaintenanceError = PostAdminStatusPageMaintenanceErrors[keyof PostAdminStatusPageMaintenanceErrors];

export type PostAdminStatusPageMaintenanceResponses = {
    /**
     * Maintenance created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Maintenance created successfully';
        data: {
            id: number;
            title: string;
            message: string;
            status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
            scheduled_start_at: number;
            scheduled_end_at: number | null;
            created_at: number;
            updated_at: number;
        };
    };
};

export type PostAdminStatusPageMaintenanceResponse = PostAdminStatusPageMaintenanceResponses[keyof PostAdminStatusPageMaintenanceResponses];

export type DeleteAdminStatusPageMaintenanceByMaintenanceIdData = {
    body?: never;
    path: {
        maintenanceId: number;
    };
    query?: never;
    url: '/admin/status-page/maintenance/{maintenanceId}';
};

export type DeleteAdminStatusPageMaintenanceByMaintenanceIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Maintenance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Maintenance not found';
    };
};

export type DeleteAdminStatusPageMaintenanceByMaintenanceIdError = DeleteAdminStatusPageMaintenanceByMaintenanceIdErrors[keyof DeleteAdminStatusPageMaintenanceByMaintenanceIdErrors];

export type DeleteAdminStatusPageMaintenanceByMaintenanceIdResponses = {
    /**
     * Maintenance deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Maintenance deleted successfully';
        data: null;
    };
};

export type DeleteAdminStatusPageMaintenanceByMaintenanceIdResponse = DeleteAdminStatusPageMaintenanceByMaintenanceIdResponses[keyof DeleteAdminStatusPageMaintenanceByMaintenanceIdResponses];

export type PutAdminStatusPageMaintenanceByMaintenanceIdData = {
    body: {
        title?: string;
        message?: string;
        status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
        scheduled_start_at?: number;
        scheduled_end_at?: number | null;
    };
    path: {
        maintenanceId: number;
    };
    query?: never;
    url: '/admin/status-page/maintenance/{maintenanceId}';
};

export type PutAdminStatusPageMaintenanceByMaintenanceIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Maintenance not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Maintenance not found';
    };
};

export type PutAdminStatusPageMaintenanceByMaintenanceIdError = PutAdminStatusPageMaintenanceByMaintenanceIdErrors[keyof PutAdminStatusPageMaintenanceByMaintenanceIdErrors];

export type PutAdminStatusPageMaintenanceByMaintenanceIdResponses = {
    /**
     * Maintenance updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Maintenance updated successfully';
        data: {
            id: number;
            title: string;
            message: string;
            status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
            scheduled_start_at: number;
            scheduled_end_at: number | null;
            created_at: number;
            updated_at: number;
        };
    };
};

export type PutAdminStatusPageMaintenanceByMaintenanceIdResponse = PutAdminStatusPageMaintenanceByMaintenanceIdResponses[keyof PutAdminStatusPageMaintenanceByMaintenanceIdResponses];

export type GetAdminStatusPageUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/status-page/updates';
};

export type GetAdminStatusPageUpdatesErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminStatusPageUpdatesError = GetAdminStatusPageUpdatesErrors[keyof GetAdminStatusPageUpdatesErrors];

export type GetAdminStatusPageUpdatesResponses = {
    /**
     * Updates retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Updates retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            type: 'general' | 'incident' | 'maintenance';
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetAdminStatusPageUpdatesResponse = GetAdminStatusPageUpdatesResponses[keyof GetAdminStatusPageUpdatesResponses];

export type PostAdminStatusPageUpdatesData = {
    body: {
        title: string;
        message: string;
        type: 'general' | 'incident' | 'maintenance';
    };
    path?: never;
    query?: never;
    url: '/admin/status-page/updates';
};

export type PostAdminStatusPageUpdatesErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PostAdminStatusPageUpdatesError = PostAdminStatusPageUpdatesErrors[keyof PostAdminStatusPageUpdatesErrors];

export type PostAdminStatusPageUpdatesResponses = {
    /**
     * Update created successfully
     */
    201: {
        success: true;
        code: 201;
        message: 'Update created successfully';
        data: {
            id: number;
            title: string;
            message: string;
            type: 'general' | 'incident' | 'maintenance';
            created_at: number;
            updated_at: number;
        };
    };
};

export type PostAdminStatusPageUpdatesResponse = PostAdminStatusPageUpdatesResponses[keyof PostAdminStatusPageUpdatesResponses];

export type DeleteAdminStatusPageUpdatesByUpdateIdData = {
    body?: never;
    path: {
        updateId: number;
    };
    query?: never;
    url: '/admin/status-page/updates/{updateId}';
};

export type DeleteAdminStatusPageUpdatesByUpdateIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Update not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Update not found';
    };
};

export type DeleteAdminStatusPageUpdatesByUpdateIdError = DeleteAdminStatusPageUpdatesByUpdateIdErrors[keyof DeleteAdminStatusPageUpdatesByUpdateIdErrors];

export type DeleteAdminStatusPageUpdatesByUpdateIdResponses = {
    /**
     * Update deleted successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Update deleted successfully';
        data: null;
    };
};

export type DeleteAdminStatusPageUpdatesByUpdateIdResponse = DeleteAdminStatusPageUpdatesByUpdateIdResponses[keyof DeleteAdminStatusPageUpdatesByUpdateIdResponses];

export type PutAdminStatusPageUpdatesByUpdateIdData = {
    body: {
        title?: string;
        message?: string;
        type?: 'general' | 'incident' | 'maintenance';
    };
    path: {
        updateId: number;
    };
    query?: never;
    url: '/admin/status-page/updates/{updateId}';
};

export type PutAdminStatusPageUpdatesByUpdateIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
    /**
     * Update not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Update not found';
    };
};

export type PutAdminStatusPageUpdatesByUpdateIdError = PutAdminStatusPageUpdatesByUpdateIdErrors[keyof PutAdminStatusPageUpdatesByUpdateIdErrors];

export type PutAdminStatusPageUpdatesByUpdateIdResponses = {
    /**
     * Update updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Update updated successfully';
        data: {
            id: number;
            title: string;
            message: string;
            type: 'general' | 'incident' | 'maintenance';
            created_at: number;
            updated_at: number;
        };
    };
};

export type PutAdminStatusPageUpdatesByUpdateIdResponse = PutAdminStatusPageUpdatesByUpdateIdResponses[keyof PutAdminStatusPageUpdatesByUpdateIdResponses];

export type GetAdminSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/settings';
};

export type GetAdminSettingsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type GetAdminSettingsError = GetAdminSettingsErrors[keyof GetAdminSettingsErrors];

export type GetAdminSettingsResponses = {
    /**
     * Settings retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Settings retrieved successfully';
        data: {
            default_theme: 'light' | 'dark' | 'auto';
        };
    };
};

export type GetAdminSettingsResponse = GetAdminSettingsResponses[keyof GetAdminSettingsResponses];

export type PutAdminSettingsData = {
    body: {
        default_theme?: 'light' | 'dark' | 'auto';
    };
    path?: never;
    query?: never;
    url: '/admin/settings';
};

export type PutAdminSettingsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Admin access required
     */
    403: {
        success: false;
        code: 403;
        message: 'Admin access required';
    };
};

export type PutAdminSettingsError = PutAdminSettingsErrors[keyof PutAdminSettingsErrors];

export type PutAdminSettingsResponses = {
    /**
     * Settings updated successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Settings updated successfully';
        data: {
            default_theme: 'light' | 'dark' | 'auto';
        };
    };
};

export type PutAdminSettingsResponse = PutAdminSettingsResponses[keyof PutAdminSettingsResponses];

export type GetUsersSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search term matched against username and display name.
         */
        q: string;
    };
    url: '/users/search';
};

export type GetUsersSearchErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        code: 400;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetUsersSearchError = GetUsersSearchErrors[keyof GetUsersSearchErrors];

export type GetUsersSearchResponses = {
    /**
     * Users retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Users retrieved successfully';
        data: Array<{
            id: number;
            username: string;
            display_name: string;
        }>;
    };
};

export type GetUsersSearchResponse = GetUsersSearchResponses[keyof GetUsersSearchResponses];

export type GetMonitorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monitors';
};

export type GetMonitorsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetMonitorsError = GetMonitorsErrors[keyof GetMonitorsErrors];

export type GetMonitorsResponses = {
    /**
     * Monitors retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitors retrieved successfully';
        data: Array<{
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
            latest_check: {
                status: 'up' | 'down' | 'degraded' | 'unknown';
                response_time_ms: number | null;
                checked_at: number | null;
            } | null;
        }>;
    };
};

export type GetMonitorsResponse = GetMonitorsResponses[keyof GetMonitorsResponses];

export type GetMonitorsByMonitorIdData = {
    body?: never;
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/monitors/{monitorId}';
};

export type GetMonitorsByMonitorIdErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Monitor not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found';
    };
};

export type GetMonitorsByMonitorIdError = GetMonitorsByMonitorIdErrors[keyof GetMonitorsByMonitorIdErrors];

export type GetMonitorsByMonitorIdResponses = {
    /**
     * Monitor retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor retrieved successfully';
        data: {
            id: number;
            name: string;
            type: 'http' | 'tcp';
            target: string;
            interval_seconds: number;
            timeout_seconds: number;
            http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
            expected_http_status: number | null;
            follow_redirects: boolean;
            verify_tls: boolean;
            is_enabled: boolean;
            created_at: number;
            latest_check: {
                status: 'up' | 'down' | 'degraded' | 'unknown';
                response_time_ms: number | null;
                checked_at: number | null;
            } | null;
            recent_checks: Array<{
                id: number;
                monitor_id: number;
                status: 'up' | 'down' | 'degraded' | 'unknown';
                response_time_ms: number | null;
                checked_at: number;
            }>;
        };
    };
};

export type GetMonitorsByMonitorIdResponse = GetMonitorsByMonitorIdResponses[keyof GetMonitorsByMonitorIdResponses];

export type GetStatusPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status-page';
};

export type GetStatusPageErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
    /**
     * Status page not found
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page not found';
    };
};

export type GetStatusPageError = GetStatusPageErrors[keyof GetStatusPageErrors];

export type GetStatusPageResponses = {
    /**
     * Status page retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Status page retrieved successfully';
        data: {
            page: {
                id: number;
                title: string;
                description: string | null;
                is_public: boolean;
                is_enabled: boolean;
                theme: 'light' | 'dark' | 'auto';
                created_at: number;
                updated_at: number;
            };
            groups: Array<{
                id: number;
                name: string;
                sort_order: number;
                monitors: Array<{
                    id: number;
                    name: string;
                    type: 'http' | 'tcp';
                    target: string;
                    display_name: string | null;
                    sort_order: number;
                    latest_check: {
                        status: 'up' | 'down' | 'degraded' | 'unknown';
                        response_time_ms: number | null;
                        checked_at: number | null;
                    } | null;
                }>;
            }>;
            ungrouped: Array<{
                id: number;
                name: string;
                type: 'http' | 'tcp';
                target: string;
                display_name: string | null;
                sort_order: number;
                latest_check: {
                    status: 'up' | 'down' | 'degraded' | 'unknown';
                    response_time_ms: number | null;
                    checked_at: number | null;
                } | null;
            }>;
            incidents: Array<{
                id: number;
                title: string;
                message: string;
                status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
                severity: 'critical' | 'major' | 'minor' | 'maintenance';
                is_resolved: boolean;
                started_at: number;
                resolved_at: number | null;
                created_at: number;
                updated_at: number;
            }>;
            maintenance: Array<{
                id: number;
                title: string;
                message: string;
                status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
                scheduled_start_at: number;
                scheduled_end_at: number | null;
                created_at: number;
                updated_at: number;
            }>;
            updates: Array<{
                id: number;
                title: string;
                message: string;
                type: 'general' | 'incident' | 'maintenance';
                created_at: number;
                updated_at: number;
            }>;
        };
    };
};

export type GetStatusPageResponse = GetStatusPageResponses[keyof GetStatusPageResponses];

export type GetStatusPageIncidentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status-page/incidents';
};

export type GetStatusPageIncidentsErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetStatusPageIncidentsError = GetStatusPageIncidentsErrors[keyof GetStatusPageIncidentsErrors];

export type GetStatusPageIncidentsResponses = {
    /**
     * Incidents retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Incidents retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
            severity: 'critical' | 'major' | 'minor' | 'maintenance';
            is_resolved: boolean;
            started_at: number;
            resolved_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetStatusPageIncidentsResponse = GetStatusPageIncidentsResponses[keyof GetStatusPageIncidentsResponses];

export type GetStatusPageMaintenanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status-page/maintenance';
};

export type GetStatusPageMaintenanceErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetStatusPageMaintenanceError = GetStatusPageMaintenanceErrors[keyof GetStatusPageMaintenanceErrors];

export type GetStatusPageMaintenanceResponses = {
    /**
     * Maintenance retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Maintenance retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
            scheduled_start_at: number;
            scheduled_end_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetStatusPageMaintenanceResponse = GetStatusPageMaintenanceResponses[keyof GetStatusPageMaintenanceResponses];

export type GetStatusPageUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status-page/updates';
};

export type GetStatusPageUpdatesErrors = {
    /**
     * Authentication required
     */
    401: {
        success: false;
        code: 401;
        message: 'Authentication required';
    };
};

export type GetStatusPageUpdatesError = GetStatusPageUpdatesErrors[keyof GetStatusPageUpdatesErrors];

export type GetStatusPageUpdatesResponses = {
    /**
     * Updates retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Updates retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            type: 'general' | 'incident' | 'maintenance';
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetStatusPageUpdatesResponse = GetStatusPageUpdatesResponses[keyof GetStatusPageUpdatesResponses];

export type GetPublicStatusPageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/status-page';
};

export type GetPublicStatusPageErrors = {
    /**
     * Status page not found or not public
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page not found or not public';
    };
};

export type GetPublicStatusPageError = GetPublicStatusPageErrors[keyof GetPublicStatusPageErrors];

export type GetPublicStatusPageResponses = {
    /**
     * Status page retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Status page retrieved successfully';
        data: {
            page: {
                id: number;
                title: string;
                description: string | null;
                is_public: boolean;
                is_enabled: boolean;
                theme: 'light' | 'dark' | 'auto';
                created_at: number;
                updated_at: number;
            };
            groups: Array<{
                id: number;
                name: string;
                sort_order: number;
                monitors: Array<{
                    id: number;
                    name: string;
                    type: 'http' | 'tcp';
                    target: string;
                    display_name: string | null;
                    sort_order: number;
                    latest_check: {
                        status: 'up' | 'down' | 'degraded' | 'unknown';
                        response_time_ms: number | null;
                        checked_at: number | null;
                    } | null;
                }>;
            }>;
            ungrouped: Array<{
                id: number;
                name: string;
                type: 'http' | 'tcp';
                target: string;
                display_name: string | null;
                sort_order: number;
                latest_check: {
                    status: 'up' | 'down' | 'degraded' | 'unknown';
                    response_time_ms: number | null;
                    checked_at: number | null;
                } | null;
            }>;
            incidents: Array<{
                id: number;
                title: string;
                message: string;
                status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
                severity: 'critical' | 'major' | 'minor' | 'maintenance';
                is_resolved: boolean;
                started_at: number;
                resolved_at: number | null;
                created_at: number;
                updated_at: number;
            }>;
            maintenance: Array<{
                id: number;
                title: string;
                message: string;
                status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
                scheduled_start_at: number;
                scheduled_end_at: number | null;
                created_at: number;
                updated_at: number;
            }>;
            updates: Array<{
                id: number;
                title: string;
                message: string;
                type: 'general' | 'incident' | 'maintenance';
                created_at: number;
                updated_at: number;
            }>;
        };
    };
};

export type GetPublicStatusPageResponse = GetPublicStatusPageResponses[keyof GetPublicStatusPageResponses];

export type GetPublicStatusPageIncidentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/status-page/incidents';
};

export type GetPublicStatusPageIncidentsErrors = {
    /**
     * Status page not found or not public
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page not found or not public';
    };
};

export type GetPublicStatusPageIncidentsError = GetPublicStatusPageIncidentsErrors[keyof GetPublicStatusPageIncidentsErrors];

export type GetPublicStatusPageIncidentsResponses = {
    /**
     * Incidents retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Incidents retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'investigating' | 'identified' | 'monitoring' | 'resolved';
            severity: 'critical' | 'major' | 'minor' | 'maintenance';
            is_resolved: boolean;
            started_at: number;
            resolved_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetPublicStatusPageIncidentsResponse = GetPublicStatusPageIncidentsResponses[keyof GetPublicStatusPageIncidentsResponses];

export type GetPublicStatusPageMaintenanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/status-page/maintenance';
};

export type GetPublicStatusPageMaintenanceErrors = {
    /**
     * Status page not found or not public
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page not found or not public';
    };
};

export type GetPublicStatusPageMaintenanceError = GetPublicStatusPageMaintenanceErrors[keyof GetPublicStatusPageMaintenanceErrors];

export type GetPublicStatusPageMaintenanceResponses = {
    /**
     * Maintenance retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Maintenance retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
            scheduled_start_at: number;
            scheduled_end_at: number | null;
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetPublicStatusPageMaintenanceResponse = GetPublicStatusPageMaintenanceResponses[keyof GetPublicStatusPageMaintenanceResponses];

export type GetPublicStatusPageUpdatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/status-page/updates';
};

export type GetPublicStatusPageUpdatesErrors = {
    /**
     * Status page not found or not public
     */
    404: {
        success: false;
        code: 404;
        message: 'Status page not found or not public';
    };
};

export type GetPublicStatusPageUpdatesError = GetPublicStatusPageUpdatesErrors[keyof GetPublicStatusPageUpdatesErrors];

export type GetPublicStatusPageUpdatesResponses = {
    /**
     * Updates retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Updates retrieved successfully';
        data: Array<{
            id: number;
            title: string;
            message: string;
            type: 'general' | 'incident' | 'maintenance';
            created_at: number;
            updated_at: number;
        }>;
    };
};

export type GetPublicStatusPageUpdatesResponse = GetPublicStatusPageUpdatesResponses[keyof GetPublicStatusPageUpdatesResponses];

export type GetPublicMonitorsByMonitorIdData = {
    body?: never;
    path: {
        monitorId: number;
    };
    query?: never;
    url: '/public/monitors/{monitorId}';
};

export type GetPublicMonitorsByMonitorIdErrors = {
    /**
     * Monitor not found or not publicly visible
     */
    404: {
        success: false;
        code: 404;
        message: 'Monitor not found or not publicly visible';
    };
};

export type GetPublicMonitorsByMonitorIdError = GetPublicMonitorsByMonitorIdErrors[keyof GetPublicMonitorsByMonitorIdErrors];

export type GetPublicMonitorsByMonitorIdResponses = {
    /**
     * Monitor retrieved successfully
     */
    200: {
        success: true;
        code: 200;
        message: 'Monitor retrieved successfully';
        data: {
            monitor: {
                id: number;
                name: string;
                type: 'http' | 'tcp';
                target: string;
                interval_seconds: number;
                timeout_seconds: number;
                http_method: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | null;
                expected_http_status: number | null;
                follow_redirects: boolean;
                verify_tls: boolean;
                is_enabled: boolean;
                created_at: number;
            };
            latest_check: {
                id: number;
                monitor_id: number;
                status: 'up' | 'down' | 'degraded' | 'unknown';
                response_time_ms: number | null;
                checked_at: number;
            } | null;
        };
    };
};

export type GetPublicMonitorsByMonitorIdResponse = GetPublicMonitorsByMonitorIdResponses[keyof GetPublicMonitorsByMonitorIdResponses];
